name: inmo_api_sdk
description: Internal API SDK package for Inmo Dart clients.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.8.1 < 4.0.0'
  flutter: '3.42.0-0.0.pre'

scripts:
  generate_api: dart run swagger_parser -f swagger_parser.yaml && dart run scripts/patch_datetime_clients.dart && dart run build_runner build --delete-conflicting-outputs --force-jit --build-filter="lib/**" && dart run scripts/generate_api_repos.dart
  generate_repos: dart run scripts/generate_api_repos.dart

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.9.2
  fpdart: ^1.1.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.0
  retrofit_generator: ^10.2.3
  swagger_parser: ^1.43.0
