// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: dart run scripts/generate_api_repos.dart

import 'package:inmo_api_sdk/src/api/export.dart';
import 'package:inmo_api_sdk/src/core/base_repo.dart';
import 'package:inmo_api_sdk/src/core/result.dart';

abstract class SearchRepo {
  Future<ResultApi<ReindexResultDto>> postSearchesListingsReindex();
  Future<ResultApi<SearchListingsResultDto>> getSearchesListings({
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  });
  Future<ResultApi<GeoSearchResultDto>> getSearchesListingsGeoRectangular({
    double? neLat,
    double? neLng,
    double? swLat,
    double? swLng,
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  });
  Future<ResultApi<GeoSearchResultDto>> getSearchesListingsGeoRadius({
    double? lat,
    double? lng,
    double? radiusKm,
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  });
  Future<ResultApi<AutocompleteResultDto>> getSearchesListingsAutocomplete({
    String? q,
  });
}

class SearchRepoImpl extends BaseRepo implements SearchRepo {
  SearchRepoImpl(this._api);

  final InmoApi _api;

  @override
  Future<ResultApi<ReindexResultDto>> postSearchesListingsReindex() {
    return executeApiCall<ReindexResultDto>(
      apiCall: () => _api.search.postApiV1SearchesListingsReindex(),
    );
  }

  @override
  Future<ResultApi<SearchListingsResultDto>> getSearchesListings({
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  }) {
    return executeApiCall<SearchListingsResultDto>(
      apiCall: () => _api.search.getApiV1SearchesListings(
        q: q,
        offerType: offerType,
        minPrice: minPrice,
        maxPrice: maxPrice,
        currencyId: currencyId,
        inmoCategoryId: inmoCategoryId,
        inmoTypeId: inmoTypeId,
        administrativeDivisionId: administrativeDivisionId,
        minBedrooms: minBedrooms,
        maxBedrooms: maxBedrooms,
        minBathrooms: minBathrooms,
        maxBathrooms: maxBathrooms,
        minTotalArea: minTotalArea,
        maxTotalArea: maxTotalArea,
        minBuiltArea: minBuiltArea,
        maxBuiltArea: maxBuiltArea,
        minLotArea: minLotArea,
        maxLotArea: maxLotArea,
        minParkingSpaces: minParkingSpaces,
        isFurnished: isFurnished,
        hasRoadAccess: hasRoadAccess,
        hasUtilities: hasUtilities,
        amenityIds: amenityIds,
        promotionTier: promotionTier,
        sortBy: sortBy,
        sortDirection: sortDirection,
        pageNumber: pageNumber,
        pageSize: pageSize,
        cursor: cursor,
      ),
    );
  }

  @override
  Future<ResultApi<GeoSearchResultDto>> getSearchesListingsGeoRectangular({
    double? neLat,
    double? neLng,
    double? swLat,
    double? swLng,
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  }) {
    return executeApiCall<GeoSearchResultDto>(
      apiCall: () => _api.search.getApiV1SearchesListingsGeoRectangular(
        neLat: neLat,
        neLng: neLng,
        swLat: swLat,
        swLng: swLng,
        q: q,
        offerType: offerType,
        minPrice: minPrice,
        maxPrice: maxPrice,
        currencyId: currencyId,
        inmoCategoryId: inmoCategoryId,
        inmoTypeId: inmoTypeId,
        administrativeDivisionId: administrativeDivisionId,
        minBedrooms: minBedrooms,
        maxBedrooms: maxBedrooms,
        minBathrooms: minBathrooms,
        maxBathrooms: maxBathrooms,
        minTotalArea: minTotalArea,
        maxTotalArea: maxTotalArea,
        minBuiltArea: minBuiltArea,
        maxBuiltArea: maxBuiltArea,
        minLotArea: minLotArea,
        maxLotArea: maxLotArea,
        minParkingSpaces: minParkingSpaces,
        isFurnished: isFurnished,
        hasRoadAccess: hasRoadAccess,
        hasUtilities: hasUtilities,
        amenityIds: amenityIds,
        promotionTier: promotionTier,
        sortBy: sortBy,
        sortDirection: sortDirection,
        pageNumber: pageNumber,
        pageSize: pageSize,
        cursor: cursor,
      ),
    );
  }

  @override
  Future<ResultApi<GeoSearchResultDto>> getSearchesListingsGeoRadius({
    double? lat,
    double? lng,
    double? radiusKm,
    String? q,
    String? offerType,
    double? minPrice,
    double? maxPrice,
    String? currencyId,
    String? inmoCategoryId,
    String? inmoTypeId,
    String? administrativeDivisionId,
    int? minBedrooms,
    int? maxBedrooms,
    int? minBathrooms,
    int? maxBathrooms,
    double? minTotalArea,
    double? maxTotalArea,
    double? minBuiltArea,
    double? maxBuiltArea,
    double? minLotArea,
    double? maxLotArea,
    int? minParkingSpaces,
    bool? isFurnished,
    bool? hasRoadAccess,
    bool? hasUtilities,
    List<String>? amenityIds,
    String? promotionTier,
    String? sortBy,
    String? sortDirection,
    int? pageNumber,
    int? pageSize,
    String? cursor,
  }) {
    return executeApiCall<GeoSearchResultDto>(
      apiCall: () => _api.search.getApiV1SearchesListingsGeoRadius(
        lat: lat,
        lng: lng,
        radiusKm: radiusKm,
        q: q,
        offerType: offerType,
        minPrice: minPrice,
        maxPrice: maxPrice,
        currencyId: currencyId,
        inmoCategoryId: inmoCategoryId,
        inmoTypeId: inmoTypeId,
        administrativeDivisionId: administrativeDivisionId,
        minBedrooms: minBedrooms,
        maxBedrooms: maxBedrooms,
        minBathrooms: minBathrooms,
        maxBathrooms: maxBathrooms,
        minTotalArea: minTotalArea,
        maxTotalArea: maxTotalArea,
        minBuiltArea: minBuiltArea,
        maxBuiltArea: maxBuiltArea,
        minLotArea: minLotArea,
        maxLotArea: maxLotArea,
        minParkingSpaces: minParkingSpaces,
        isFurnished: isFurnished,
        hasRoadAccess: hasRoadAccess,
        hasUtilities: hasUtilities,
        amenityIds: amenityIds,
        promotionTier: promotionTier,
        sortBy: sortBy,
        sortDirection: sortDirection,
        pageNumber: pageNumber,
        pageSize: pageSize,
        cursor: cursor,
      ),
    );
  }

  @override
  Future<ResultApi<AutocompleteResultDto>> getSearchesListingsAutocomplete({
    String? q,
  }) {
    return executeApiCall<AutocompleteResultDto>(
      apiCall: () => _api.search.getApiV1SearchesListingsAutocomplete(
        q: q,
      ),
    );
  }

}
